### ISSUE TITLE
Cognito Email sign-in tutorial does not mention awsconfiguration.json

### ISSUE THREAD

**Issue by fahlmant** [awsdocs/aws-mobile-developer-guide#14]
In the document ` aws-mobile-developer-guide/doc_source/add-aws-mobile-user-sign-in.rst`, when following the `Setup Email & Password Login in your Mobile App`, there is no mention of using an `awsconfiguration.json` file. It simply says to run the activity and it should work.

**Comment by dzucker-amzn** [comment]
Thanks for pointing this out. We added a new step to the docs about updating your app's copy of awsconfiguration.json when you add a new identity provider to your Mobile Hub project.

**Comment by dzucker-amzn** [comment]
I believe your issue is addressed so I'll close it now. Please let me know if you have any further questions
