### ISSUE TITLE
how-to-android-dynamodb-scan missing from source documentaation

### ISSUE THREAD

**Issue by matszal** [awsdocs/aws-mobile-developer-guide#16]
Hi there. 
Im trying to perform some dynamodb scan from my android app and wonderiing if I could get that document please? It seems to be missing from repo?
Reagrds Mateusz.

**Comment by dzucker-amzn** [comment]
Thanks much for your request. Adding a How-to item for Amazon Dynamodb scan is on our backlog and this input will help us prioritize.

Meantime, you might find the following java content from the Amazon DynamoDB Developer Guide helpful.

https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBMapper.QueryScanExample.html

Dan Zucker
AWS Mobile Senior Programming Writer
http://aws.amazon.com/mobile

**Comment by matszal** [comment]
@dzucker-amzn Dan thank you very much for a quick reply. I'll look up your example shortly.

**Comment by dzucker-amzn** [comment]
Closing this issue: This request to add content about dynamoBD scan using the AWS Mobile SDK has been added to our backlog. Please reopen if there are further questions.
