### ISSUE TITLE
Cannot resolve symbol 'AWSMobileClient' from sample code

### ISSUE THREAD

**Issue by siddhantg-cbre** [awsdocs/aws-mobile-developer-guide#18]
Line block ```voiceView.getViewAdapter().setCredentialProvider(AWSMobileClient.getInstance().getCredentialsProvider());```

returns error message `Cannot resolve symbol 'AWSMobileClient'`

`com.amazonaws.mobile.client.AWSMobileClient'` doesn't seem to exist under `com.amazonaws:aws-android-sdk-lex:2.6.+@aar`

**Comment by dzucker-amzn** [comment]
@Siddhartha-cbre  - Thanks much for helping us improve these docs!

You'll also need the dependencies and library import for AWSMobileCLient described in getting-started.rst (see below). Based on your comment, I'll update the docs to include the AWSMobileClient bits in the code snippets. 

Gradle:

dependencies {
    implementation ('com.amazonaws:aws-android-sdk-mobile-client:2.6.+@aar') { transitive = true)    
    implementation ('com.amazonaws:aws-android-sdk-lex:2.6.+@aar') {transitive = true}
}

Imports:
 import com.amazonaws.mobile.client.AWSMobileClient;
 import com.amazonaws.mobileconnectors.lex.interactionkit.Response;
 import com.amazonaws.mobileconnectors.lex.interactionkit.config.InteractionConfig;
 import com.amazonaws.mobileconnectors.lex.interactionkit.ui.InteractiveVoiceView;

**Comment by dzucker-amzn** [comment]
Also, per getting-started.rst, you'll also need to instantiate the AWSMobileClient before calling it:

        AWSMobileClient.getInstance().initialize(this, new AWSStartupHandler() {
            @Override
            public void onComplete(AWSStartupResult awsStartupResult) {
                Log.d("YourMainActivity", "AWSMobileClient is instantiated and you are connected to AWS!");
            }
        }).execute();

**Comment by siddhantg-cbre** [comment]
Thanks @dzucker-amzn that makes more sense now.
You'd also probably need 
```
import com.amazonaws.mobile.client.AWSStartupHandler;
import com.amazonaws.mobile.client.AWSStartupResult;
```
for the instantiation code

**Comment by dzucker-amzn** [comment]
We added a more complete code sample that includes imports and context about instantiating AWSMobileClient. Thanks again for pointing this out.
