### ISSUE TITLE
Copying and pasting this code will not even compile on kotlin

### ISSUE THREAD

**Issue by pymblesoftware** [awsdocs/aws-mobile-developer-guide#23]
This line specifically:
txObserver.transferListener = object : TransferListener() {
Gives:
Cannot access 'transferListener': it is private in 'TransferObserver'
Also complains that TransferListener does not have a constructor

**Comment by dzucker-amzn** [comment]
@pymblesoftware Thanks for alerting us. Looking into this now.

**Comment by dzucker-amzn** [comment]
@pymblesoftware Thanks again for your call out. Publishing updated example code now.
