### ISSUE TITLE
Missing description for the lambda environment: {}

### ISSUE THREAD

**Issue by nawwa** [awsdocs/aws-mobile-developer-guide#26]
Hello, 

I export my MobileHub project and my lambdas are exported without their environment variable.
I also want to import a mobile hub project file, the lambda definition in the file looks like this  :

I took the "environement : {..}" from the official documentation, when i try to import I have the error "Failed to complete requested operation.
There was an issue processing your YAML file. Please ensure that it exists and is formatted correctly."

Nothing is written about the environment variable.. How can we format it ?

```
...
...
paths:
          /admin: !com.amazonaws.mobilehub.v0.Function
            codeFilename: uploads/admin-20180516134533.zip
            description: "Handler for calls to resource path : /admin/{proxy+}"
            enableCORS: true
            environment:
              {MENU_TABLE_NAME}: ___DYNAMIC_PREFIX___{-bbq_menu_item}
              {ORDERS_TABLE_NAME}: ___DYNAMIC_PREFIX___{-bbq_orders}
              {RESTAURANTS_TABLE_NAME}: ___DYNAMIC_PREFIX___-{bbq_restaurants}
            handler: index.handler
            hashcode: RUIml4BcWjp0ddmglSfBz5Ls9paqJLPjtN8Pupx8DBg=
            memorySize: "128"
            modified: "2018-05-16T12:59:24.216+0000"
            name: admin
          /admin: !com.amazonaws.mobilehub.v0.Function
            codeFilename: uploads/admin-20180516134533.zip
            description: "Handler for calls to resource path : /admin/{proxy+}"
            enableCORS: true
            environment:
              {MENU_TABLE_NAME}: ___DYNAMIC_PREFIX___{-bbq_menu_item}
              {ORDERS_TABLE_NAME}: ___DYNAMIC_PREFIX___{-bbq_orders}
              {RESTAURANTS_TABLE_NAME}: ___DYNAMIC_PREFIX___-{bbq_restaurants}
            handler: index.handler
            hashcode: RUIml4BcWjp0ddmglSfBz5Ls9paqJLPjtN8Pupx8DBg=
            memorySize: "128"
            modified: "2018-05-16T12:59:24.216+0000"
            name: admin
...
...
```

**Comment by dzucker-amzn** [comment]
@nawwa Apologies if I am covering ground you already know, but just to make sure:

Lambda API handlers for the APIs configured in your Mobile Hub project's Cloud Logic feature must be manually exported. Steps are described here:

https://docs.aws.amazon.com/aws-mobile/latest/developerguide/project-import-export-manual.html#import-export-cloud-logic

You can find the basics about Lambda environmental variables here:

https://docs.aws.amazon.com/lambda/latest/dg/tutorial-env_cli.html

If those  don't provide the information you need, could you add a bit more detail about where you are stuck?

**Comment by swaminator** [comment]
@nawwa : Would love to chat with you on the phone if you have time?

**Comment by dzucker-amzn** [comment]
The link I provided was a typo, should have been:

https://docs.aws.amazon.com/aws-mobile/latest/developerguide/project-import-export-manual.html#import-export-cloud-logic

**Comment by nawwa** [comment]
Hello guys, thanks for your answers !

I posted the same issue on AWS support forum, i got an answer : 

https://forums.aws.amazon.com/thread.jspa?messageID=855603&#855603
I guess it will work.

But I think the documentation is not very clear about this.. !
Thanks again
