### ISSUE TITLE
React-native clients?

### ISSUE THREAD

**Issue by siddhantg-cbre** [awsdocs/aws-mobile-developer-guide#28]
Is there a react-native client for this? Or is there a project under active development?

**Comment by dzmedia** [comment]
@Siddhartha-cbre The AWS Mobile offering for React Native is called AWS Amplify. Please take a look at https://aws.github.io/aws-amplify/media/create/react-native-apps

**Comment by siddhantg-cbre** [comment]
I found an Amplify+Lex tutorial for react-native here https://aws.github.io/aws-amplify/media/interactions_guide#create-your-chatbot but it doesn't seem to have any support for a voice bot, just text only. Would having a 'react-native' tab in the guide at https://docs.aws.amazon.com/aws-mobile/latest/developerguide/add-aws-mobile-conversational-bots.html#add-aws-mobile-conversational-bots-app for voice and text bots make it more complete?

**Comment by dzucker-amzn** [comment]
@Siddhartha-cbre The AWS Mobile offering for React Native is called AWS Amplify. Please take a look at https://aws.github.io/aws-amplify/media/create/react-native-apps

That's good feedback about voice chatbot. I'd suggest providing that in an issue in https://github.com/aws/aws-amplify or bringing it up using the open chat link on the amplify site.
