### ISSUE TITLE
iOS Notes App sign up issues

### ISSUE THREAD

**Issue by sirshannon** [awsdocs/aws-mobile-developer-guide#29]
I'm working through [AWS Mobile > Android and iOS > Tutorials > iOS Notes App > Authentication](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/tutorial-ios-aws-mobile-notes-auth.html).  

Under "Add User Sign-in to the AWS Mobile Hub Project", the 6th and 7th steps are
>6. Choose *Email and Password*.
>7. Scroll to the bottom and then Choose *Create user pool*.
- If you follow these directions, you are shown an error message when you click *Create user pool*: "You must select at least one username attribute: email, or phone number." because after step 6, you must also check a box for "Email" or "Password." I do not know which of these should be chosen but at least one must be chosen.
- Step 7 above should be "Scroll to the bottom and then choose *Create user pool*." not "Scroll to the bottom and then Choose *Create user pool*."

After choosing the "Email" checkbox under "Email and Password", and adding the required code, the app launches and shows a sign-in form as expected. Tapping "Create a new account" shows a sign-up form as expected.
- The sign-up form has "User Name", "Password", "Email", "Phone Number" even though the only fields that should be shown are "Email" and "User Name." 
- Attempting to sign up by filling in the "Email" and "Password" fields fails with the message that "username" (not "User Name" as shown on the form) and password are required.
- Putting a User Name in the "User Name" field throws an error saying "Username must be email" (not "User Name" as the field is labeled).
- If Email is required as the user name (as your instructions intend) then this form should not have an Email field and the "User name" form field label should say "Email" (or should at least match the error messages version "username")
- The form field labels do not correctly hide when user tabs to next field. The textbox gets focus and you can type in it but you can't see that until you tap the field, which moves the label out of the way, allowing you to see that you were typing in the textbox as intended.
- If this form is going to be used in this example, the example should be changed so that the form works and makes sense. Instead of using Email as User Name, the account should use a username and password. The way this form works and the way the example intends for it to work are at odds with each other. The only way this form makes sense is if there are exactly 4 possible fields: User name (that is not an email address), password, email address, and phone number.

**Comment by sirshannon** [comment]
Also, how do you sign out after signing in? Closing the app, force quitting the app, even deleting the app from the device does not sign the user out, as far as I can tell.

**Comment by dzucker-amzn** [comment]
@sirshannon Thanks for your detailed feedback and questions. The tutorial is indeed out of sync with the console, regrets for the frustration, we'll work on getting that fixed. 

RE: sign-out - please see:

https://docs.aws.amazon.com/aws-mobile/latest/developerguide/add-aws-mobile-user-sign-in.html#auth-sign-out

and 

https://docs.aws.amazon.com/aws-mobile/latest/developerguide/how-to-user-sign-in-sign-out.html

**Comment by dzucker-amzn** [comment]
Regarding your comments about the tutorial steps:

- to replicate the configuration the tutorial expects 

1. Select the **Username** radio button and the **Phone** checkbox under it.
2. Then select **Required** for **Multi-factor authentication**
<img width="373" alt="image" src="https://user-images.githubusercontent.com/19578266/42533366-78256ba4-843e-11e8-8ed8-4f2d696ec946.png">
3. Finally, switch **Require user sign-in?** to **Yes**

<img width="376" alt="image" src="https://user-images.githubusercontent.com/19578266/42533519-fb927798-843e-11e8-9c44-cd7748ebab81.png">

I believe that will answer most of your issues, but will leave the issue open for the time being in case you have further follow up.
