### ISSUE TITLE
How to sign in without AWS UI in Android?

### ISSUE THREAD

**Issue by angli13** [awsdocs/aws-mobile-developer-guide#32]
I've been helping one of my developers just to find the correct documentation on how to sign in without the built in UI in Android. We already have a sign in UI built and we need to use that design but I cant find any documentation on how to do this, at least on the latest version. Is this even possible using the last SDK?

**Comment by dzucker-amzn** [comment]
@angli13 Thanks for your query! I suggest you take a look at:

https://docs.aws.amazon.com/cognito/latest/developerguide/tutorial-integrating-user-pools-android.html

https://github.com/awslabs/aws-sdk-android-samples/tree/master/AmazonCognitoYourUserPoolsDemo

I'll close this, but feel free to reopen if you have further need.

**Comment by angli13** [comment]
Thanks for the response, but I still don't know where to start. 
The first link you point me to (https://docs.aws.amazon.com/es_es/aws-mobile/latest/developerguide/add-aws-mobile-user-sign-in.html) explains how to use the built-in UI which is the opposite of what we need.
The second one is a great example of how to implement user pools, but I want to use federated identities with user pools and facebook, just like Mobile Hub does it, just not using the built-in UI.
It seems like the only way to understand this is going through different docs and do a "mix" between them to get a better understanding of how it works. The problem is that I don't know what are the updated docs for this, it seems all the updated docs point to using Cognito Auth o the built-in UI, none of the docs talk about this. 
Is there something I'm missing here? I would think this is a common requirement for other developers but it seems I'm drowning between all (they are a lot) your docs about how to implement Cognito.
I've already implemented this authentication on iOS, and the only way was to clone AWS Auth UI and modify the UI to fit our design, that was the easiest way to do it, maybe that would be a good idea for the future of AWS Mobile.
Just to finish, is there one single doc where I can understand how all the services of AWS Mobile for authentication work? There is a lot to understand and the tools are named very similar, even the classes on the SDK are called very similar.
Thanks

**Comment by dzucker-amzn** [comment]
@angli13 Regrets that we don't have the single page you describe. Please take a look at:

https://docs.aws.amazon.com/aws-mobile/latest/developerguide/how-to-cognito-integrate-an-existing-identity-pool.html 

https://docs.aws.amazon.com/cognito/latest/developerguide/getting-credentials.html

https://docs.aws.amazon.com/cognito/latest/developerguide/accessing-aws-services.html

**Comment by adrianhall** [comment]
You can also check out the following blog: https://proandroiddev.com/building-a-custom-auth-ui-for-amazon-cognito-in-kotlin-9d6fc5e2f182 which walks you through it and has an attached example project.

**Comment by RWOverdijk** [comment]
@adrianhall Hey! Where did that blog post go?

**Comment by adrianhall** [comment]
No idea what happened to ProAndroidDev article, however I archive all my blog posts on https://adrianhall.github.io and have a whole AWS tag on there.
