### ISSUE TITLE
Difference between task.result and task.complete?

### ISSUE THREAD

**Issue by semerda** [awsdocs/aws-mobile-developer-guide#34]
(a) What's the best way to check when S3 upload not just uploaded but is ready for query?
if (task.result) { or if (task.completed) { ?

(b) Is there a difference between the 2?

(c) Or 3rd option, check if etag value is inside task.result and then mark the upload as completed?

**Comment by semerda** [comment]
AFTER uploading to S3 using accelerated upload, task.result is called (as shown in screenshot) and _completed == YES. You’d assume the S3 object is ready and available. But we are missing the ETag. ETag points to the object in S3. This is not right? I cannot trust task.result or task.completed to know when object is available on S3? Please help me understand this.

<img width="567" alt="Screen Shot 2019-04-01 at 6 22 25 PM" src="https://user-images.githubusercontent.com/557108/55369519-be475f00-54ab-11e9-95fb-eea26b41ab82.png">

**Comment by awsdan** [comment]
Issue is over a year and a half old. Closing.
